pipeline {
    agent {
        label 'master'
    }
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws_key_access')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_key')
    }
    stages {
        stage('Build Microservices Queue') {
            steps {
                dir('queue_microservice/terraform') {
                    sh 'terraform init'
                    sh 'terraform apply --auto-approve'
                }
            }
            post {
                failure {
                    sh 'terraform destroy --auto-approve'
                    echo 'Infrastructure deployment failed, please review the logs'
                }
                success {
                    echo 'Microservices queue deployed!'
                }
            }
        }
        stage('Test Microservices Queue Workflow') {
            steps {
                dir('queue_microservice/scripts') {
                    sh 'chmod u+x start_execution.sh'
                    sh './start_execution.sh'
                }
            }
            post {
                failure {
                    echo 'Testing Failed! Please check the logs'
                }
                success {
                    echo 'Testing has been successful!'
                    sleep(time: 5, unit: "MINUTES")
                    echo '5 minutes until proceed with the Clean Infrastructure & Workspace stage'
                }
            }
        }
        stage('Clean Infrastructure & Workspace') {
            steps {
                dir('queue_microservice/terraform') {
                    sh 'terraform destroy --auto-approve'
                    echo 'Infrastructure destroyed!'                       
                    cleanWs()                                                  
                    echo 'Jenkins Workspace has been wipe out'                 
                }  
            }			
        }
    }
}
